### PR TITLE
Use rem instead of px in the Media Indicator SVGs

### LINKED ISSUE #784: Brand and Media Indicator not scaling on text resize.
**Describe the bug**
If the text is resized to 200%, the `Brand` and `Media indicator` SVGs are very small.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to `Firefox preferences -> Fonts and Colours`
2. Change font size to `72px`
3. Look at the Brand and any story with Media Indicator

**Expected behaviour**
They should scale proportionally with the font-size.

**Screenshots**
text-resized

60676190-2ecc9600-9e76-11e9-8534-cfef51c7b5c6

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #784

**Overall change:** 
 In order to make the Media Indicator scale as the text is resized, they should use `rem` instead of `px`.

**Code changes:**
- Use `VideoMediaIcon` and `AudioMediaIcon` styled components with the width and height in `rem`s.
- Update snapshots

Screenshot 2019-07-05 at 13 34 48
Screenshot 2019-07-05 at 13 35 40

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

File: packages/components/psammead-media-indicator/src/mediaIcons.jsx [hunk 1]
```diff
@@ -9,17 +9,27 @@ const MediaIcon = styled.svg`
   fill: ${C_EBON};
 `;
 
+const VideoMediaIcon = styled(MediaIcon)`
+  width: 0.75rem;
+  height: 0.75rem;
+`;
+
+const AudioMediaIcon = styled(MediaIcon)`
```
Comment (dr3) [inline packages/components/psammead-media-indicator/src/mediaIcons.jsx:17]: I have a feeling the reason we did html attributes for width and height before, not CSS, was to ensure the icons dont go huge when css is disabled. This way, _i think_ they go full screen with you disable css. Havent checked though

Comment (DenisHdz) [reply packages/components/psammead-media-indicator/src/mediaIcons.jsx:17]: True, so then we will have to accept that they don't scale when the text is resized or find another workaround because as far as I know, we can't put `rem` directly in the HTML attributes.

Comment (dr3) [reply packages/components/psammead-media-indicator/src/mediaIcons.jsx:17]: Could we have both? width attribute for no css, width css for with css?

Comment (DenisHdz) [reply packages/components/psammead-media-indicator/src/mediaIcons.jsx:17]: That worked 💅🏼

**Review by dr3 — APPROVED** [review]

**Review by j-pendlebury — APPROVED** [review]

**Comment by david-boydell** [comment]
Great, this is ready for merge
