### PR TITLE
Fixes most read rank overlapping the link

### LINKED ISSUE #9051: Overlap in Most Read component
**Describe the bug**

Overlap in the Most Read component on Arabic site:

image

https://www.bbc.com/arabic/middleeast-56548177

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by mukama**
Resolves https://github.com/bbc/simorgh/issues/9051

**Overall change:** 
This PR fixes an overflow happening on most read rank.

**Code changes:**

- Replaced `min-width` with `flex` so that the rank and the link do not overlap.
- Updates corresponding snapshots.

**Before**
image

**After**
image

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

File: packages/components/psammead-most-read/src/Rank/index.jsx [hunk 1]
```diff
@@ -82,58 +82,65 @@ const isFiveOrTen = ({ listIndex, service, numberOfItems }) => {
...
   @media (min-width: ${GEL_GROUP_1_SCREEN_WIDTH_MIN}) and (max-width: ${GEL_GROUP_1_SCREEN_WIDTH_MAX}) {
-    min-width: ${props =>
-      listHasDoubleDigits(props.numberOfItems)
-        ? getRankMinWidth(props).group1WithOneColumn
-        : getRankMinWidth(props).group1};
+    flex: 0 0
+      ${props =>
+        listHasDoubleDigits(props.numberOfItems)
+          ? getRankMinWidth(props).group1WithOneColumn
+          : getRankMinWidth(props).group1};
```
Comment (andrewscfc) [inline packages/components/psammead-most-read/src/Rank/index.jsx]: Can you explain how this behaves differently to `min-width`? From the flex docs it seems to me you have configured the rank to:
- not grow
- not shrink
- have a min width as calculated in the function?

File: packages/components/psammead-most-read/src/Rank/index.jsx [hunk 2]
```diff
@@ -82,58 +82,65 @@ const isFiveOrTen = ({ listIndex, service, numberOfItems }) => {
 
 const OneColumnWrapper = styled.div`
   @media (max-width: ${GEL_GROUP_0_SCREEN_WIDTH_MAX}) {
-    min-width: ${props =>
-      listHasDoubleDigits(props.numberOfItems)
-        ? getRankMinWidth(props).group0WithOneColumn
-        : getRankMinWidth(props).group0};
+    flex: 0 0
```
Comment (HarveyPeachey) [inline packages/components/psammead-most-read/src/Rank/index.jsx]: I'm not sure if this is the right approach. I worked partly on this and the code is a bit all over the place for Most Read. This is due to having the implementation cater for Most Read pages and also the Most Read component on articles whilst having different sizing for the number typographies. I think what needs to be done is changing the hard coded rank number min widths in [`rankMinWidth.js`](https://github.com/bbc/psammead/blob/latest/packages/components/psammead-most-read/src/utilities/rankMinWidth.js).

As it's Arabic, it's considered a [medium font](https://github.com/bbc/psammead/blob/ff1a3965c1907f3ed1d11a99acc49dec7acaa429/packages/components/psammead-most-read/src/utilities/rankMinWidth.js#L11) size service. So you would want to change one of the column values that have a key of small in [here](https://github.com/bbc/psammead/blob/ff1a3965c1907f3ed1d11a99acc49dec7acaa429/packages/components/psammead-most-read/src/utilities/rankMinWidth.js#L75). Small being the smaller size for articles and default being the size for most read pages. This makes sure the text all aligns squarely.

I can jump on a call if you need any help with this

**Review by HarveyPeachey — CHANGES_REQUESTED** [review]

**Review by HarryVerhoef — COMMENTED** [review]
I think this does fix the issue, but also agree with @HarveyPeachey that if there is already logic in place for generating different `min-width`s depending on the text size and number of digits, then perhaps it would be better to correct that logic instead

File: packages/components/psammead-most-read/src/Rank/index.jsx (hunk 1 above)
Comment (mukama) [reply packages/components/psammead-most-read/src/Rank/index.jsx]: Thank you for the review @andrewscfc. By setting flex-grow and flex-shrink to `0` the text will grow/shrink relative to the `flex-basis` of the rank . `min-width` alone on a flex child is the reason the overlap happens.

File: packages/components/psammead-most-read/src/Rank/index.jsx (hunk 2 above)
Comment (mukama) [reply packages/components/psammead-most-read/src/Rank/index.jsx]: Thank you for the review @HarveyPeachey.

The reason for using `flex-basis` instead of `min-width` is that some browsers have trouble sizing flex items inside flex containers. Also, I have set `flex-grow` and `flex-shrink` to `0` to mimic `min-width`. Doing it this way allows us to specify the initial size of the rank element, before anything else is computed thereby avoiding overlaps.

Comment (mukama) [reply packages/components/psammead-most-read/src/Rank/index.jsx]: I am happy to jump on a call :)

**Comment by mukama** [comment]
> I think this does fix the issue, but also agree with @HarveyPeachey that if there is already logic in place for generating different `min-width`s depending on the text size and number of digits, then perhaps it would be better to correct that logic instead

Hi @HarryVerhoef. The logic is being reused in the refactor :)

File: packages/components/psammead-most-read/src/Rank/index.jsx (hunk 2 above)
Comment (HarveyPeachey) [reply packages/components/psammead-most-read/src/Rank/index.jsx]: Hmm if the approach works and others are happy then I think it might be fine. My main concern is that changing everything from `min-width` to `flex-basis` would mean we would need to check all 41 services and the variations of most read which include [front page](https://www.bbc.com/arabic), [most read page](https://www.bbc.com/arabic/popular/read) and story pages. Whilst also checking if any browser quirks could be introduced

**Comment by HarryVerhoef** [comment]
> Hi @HarryVerhoef. The logic is is being reused in the refactor :)

Thanks @mukama, what I meant was is it not possible to adjust the values produced by the existing logic so that a larger `min-width` is given in the case of double digits in Arabic? That way we wouldn't have to worry about any implications of changing `min-width` to `flex-basis`, and the change to existing code is minimised.

I think the following line needs to be added to the psammead-most-read changelog in order to get changeScanner to pass:

```js
| 6.0.28 | [PR#4471](https://github.com/bbc/psammead/pull/4471) Fixes most read rank overlapping link |
```

Also, might be worth considering changing the version to `6.1.0`, imo this PR brings enough relative change to warrant a minor release. Would be interested to see what others think.

File: packages/components/psammead-most-read/src/Rank/index.jsx (hunk 2 above)
Comment (mukama) [reply packages/components/psammead-most-read/src/Rank/index.jsx]: Yeah, it's a bit of an arduous task testing all services and their variations but visually it should remain as it was with `min-width` except in cases where we had overlaps.

**Comment by mukama** [comment]
Thanks for the reviews and suggestion @HarryVerhoef and @HarveyPeachey. I have increased the size of the `min-width` instead of using `flex-basis` because of the complexities this might bring :)

**Review by HarveyPeachey — APPROVED** [review]
Hopefully some point down the line we can refactor this big boi

**Review by rebeccamcginn — APPROVED** [review]
