### PR TITLE
Fix cursor on placeholder for no-js

### LINKED ISSUE #2805: Fix placeholder cursor when JS is disabled
**Describe the bug**
When a user has javascript disabled, and they attempt to hover over a mediaplayer placeholder, their cursor will change to a pointer, indicating that it is a clickable element. In this instance, this is not the case, as the mediaplayer cannot play. 

We need to update the `StyledPlaceholder` styling to remove the `cursor: pointer` property when no-JS is enabled.

https://github.com/bbc/psammead/blob/c5b0daa6429d695daf67712e87781dfb120fbf17/packages/components/psammead-media-player/src/Placeholder/index.jsx#L9-L16

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to `/news/articles/c3wmq4d1y3wo`
2. Disable JavaScript
3. Hover over the media player
4. See pointer behaviour

**Expected behaviour**
When hovering over the placeholder, the cursor behaviour / appearance should not change.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by 12**
Resolves #2805 

**Overall change:** Fixes the cursor when hovering on a placeholder for media when javascript is disabled. Current appearance is to show a pointer, however this should not be the case when javascript is disabled, as the user cannot click to play.

**Code changes:**

- When JS is disabled, reset `cursor` property to `default`.

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

File: packages/components/psammead-media-player/src/Placeholder/index.jsx [hunk 1]
```diff
@@ -13,6 +13,14 @@ const StyledPlaceholder = styled.div`
   left: 0;
   width: 100%;
   height: 100%;
+
+  ${({ noJsClassName }) =>
+    noJsClassName &&
+    css`
+      .${noJsClassName} & {
```
Comment (DenisHdz) [inline packages/components/psammead-media-player/src/Placeholder/index.jsx]: Do you need this `.${noJsClassName} & {`?

Comment (12) [reply packages/components/psammead-media-player/src/Placeholder/index.jsx]: Have updated.

**Review by DenisHdz — APPROVED** [review]

**Review by HarveyPeachey — APPROVED** [review]
LGTM
