### PR TITLE
Storybook helpers v5

### LINKED ISSUE #1668: Storybook Input Provider - Incorrect Service Names
**Describe the bug**
The input provider currently has the following issues:

- Incorrect service names - the `indonesia` service is called `indonesian` and `afaanoromoo` is called `afaanOromoo` (wrong case)
- Cannot configure default service - hardcoded to `news` - assumes every component supports this service

### PR DESCRIPTION
**Pull request by ryanmccombe**
Resolves https://github.com/bbc/psammead/issues/1668

**Overall change:** _Update service names for parity with Simorgh, and add option to set default service._

**Code changes:**

- _Renamed `indonesian` to `indonesia`._
- _Renamed `afaanOromoo` to `afaanoromoo`._
- _`inputProvider` now allows a default service to be configured, rather than always using `news`_

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

File: packages/utilities/psammead-storybook-helpers/src/input-provider.jsx [hunk 1]
```diff
@@ -4,14 +4,23 @@ import { Helmet } from 'react-helmet';
 import * as scripts from '@bbc/gel-foundations/scripts';
 import LANGUAGE_VARIANTS from './text-variants';
 
-const inputProvider = (slots, componentFunction, services) => () => {
+const inputProvider = (
+  slots,
+  componentFunction,
+  services,
+  options = {},
```
Comment (jroebu14) [inline packages/utilities/psammead-storybook-helpers/src/input-provider.jsx:11]: are we expecting more options? what if this arg was just `defaultService = 'news'`

Comment (dr3) [reply packages/utilities/psammead-storybook-helpers/src/input-provider.jsx:11]: Yeah, ide almost prefer 
```
(slots, componentFunction, services)
```
-> 
```
({ slots, componentFunction, services, defaultService })
```
or put `services` inside options, as its optional

Comment (ryanmccombe) [reply packages/utilities/psammead-storybook-helpers/src/input-provider.jsx:11]: I don't know if we'll need to add more arguments to this eventually, but I think the amount of arguments here is already problematic - you can see that in the test file where there are `null` parameters being passed in everywhere

Made the 4th an options object to stop the problem getting any further out of hand - https://github.com/ryanmcdermott/clean-code-javascript#function-arguments-2-or-fewer-ideally

Comment (ryanmccombe) [reply packages/utilities/psammead-storybook-helpers/src/input-provider.jsx:11]: @dr3 agree that all the arguments should just be one object eventually, but that's a massive breakign change that would require updating all stories in Simorgh and Psammead to a new API.  Not sure that's in scope for media pod?  We just want our page on storybook 😢

Comment (ryanmccombe) [reply packages/utilities/psammead-storybook-helpers/src/input-provider.jsx]: https://github.com/ryanmcdermott/clean-code-javascript#function-arguments-2-or-fewer-ideally

Comment (chris-hinds) [reply packages/utilities/psammead-storybook-helpers/src/input-provider.jsx:11]: @ryanmccombe definitely not in scope for the media pod or this PR really. Could you raise an issue about that refactor though so it can be picked up and looked into by the core pod at a later date.

Comment (ryanmccombe) [reply packages/utilities/psammead-storybook-helpers/src/input-provider.jsx:11]: https://github.com/bbc/simorgh/issues/3077

**Review by dr3 — APPROVED** [review]

File: packages/utilities/psammead-storybook-helpers/CHANGELOG.md [hunk 2]
```diff
@@ -3,6 +3,7 @@
 <!-- prettier-ignore -->
 | Version | Description |
 |---------|-------------|
+| 5.0.0 | [PR#1714](https://github.com/bbc/psammead/pull/1714) Renamed `indonesian` to `indonesia` and `afaanOromoo` to `afaanoromoo`.  Input provider now has an optional 4th argument that allows the default service to be configured |
```
Comment (pjlee11) [inline packages/utilities/psammead-storybook-helpers/CHANGELOG.md:6]: Any reason you went with `5.0.0` rather than `4.1.0`, IMO this doesn't need to be a major change

Comment (ryanmccombe) [reply packages/utilities/psammead-storybook-helpers/CHANGELOG.md:6]: I believe the service rename part of this is a breaking change - previously, "indonesian" appeared on the dropdown, and got passed to your component if someone selected it.  Now, it will be "indonesia"

At least I think that's true - the only thing that makes me doubt it is surely some components would have errored if you passed an invalid service name in the current version?

But maybe nobody noticed it as these services weren't used

Comment (pjlee11) [reply packages/utilities/psammead-storybook-helpers/CHANGELOG.md:6]: Ahhh yeah, it is likely those services haven't been used/bugs haven't been spotted.

**Review by pjlee11 — APPROVED** [review]

**Comment by ryanmccombe** [comment]
No testing needed here - just some behind-the-scenes work to add functionality that will be used for future PRs
