### PR TITLE
Podcast promo design fixes

### LINKED ISSUE #4212: Podcast Promo colour contrast and column span design fixes
Resolved by https://github.com/bbc/psammead/pull/4214

**Describe the bug**
Following a recent a11y swarm, a few design issues were uncovered with the podcast promo component:

- [x]  Image looks like it only spans one column on group A and B breakpoints. It should be bigger. 
- [x] Font weight on summary and 'Episode' text should be 'Normal' 
- [x] Not sure if there is a drop shadow on the white box. There should be.
- [x] Heading fails colour contrast - the grey is too light on visited state. Check colours of bg card as well as link text. Designs were wrong-  should have been using `C_METAL`. Now updated.
           

Designs to assist: https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/dashboard?q=podcast%20promo

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://bbc.github.io/psammead/?path=/story/components-podcastpromo--default'

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by emilysaffron**
Resolves #4212

**Overall change:** 
Fixed flex behaviour to respect the size assigned to image
Drop shadow added for the card
Colour for visited state of header now C_METAL to pass colour contrast

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

File: packages/components/psammead-podcast-promo/src/components/card.jsx [hunk 1]
```diff
@@ -1,11 +1,12 @@
 import styled from '@emotion/styled';
-import { C_GHOST } from '@bbc/psammead-styles/colours';
+import { C_GHOST, C_EBON } from '@bbc/psammead-styles/colours';
 import { GEL_GROUP_4_SCREEN_WIDTH_MIN } from '@bbc/gel-foundations/breakpoints';
 
 const Card = styled.div`
   position: relative;
   background-color: ${C_GHOST};
   display: flex;
+  box-shadow: 0 0 5px 5px ${C_EBON}08;
```
Comment (pharingee) [inline packages/components/psammead-podcast-promo/src/components/card.jsx]: Is the  `08` at the end of this line a typo?

**Review by pharingee — APPROVED** [review]

File: packages/components/psammead-podcast-promo/src/components/card.jsx (hunk 1 above)
Comment (RichardPK) [reply packages/components/psammead-podcast-promo/src/components/card.jsx]: Nah that's adding transparency of 0.03 to the `C_EBON` hash value - it's intentional 👍

**Comment by RichardPK** [comment]
Hey @emilysaffron - https://github.com/bbc/psammead/pull/4214/commits/01fb91d738e27543a23c85c16958692fa0b3c853 (`fix boxshadow style typo`) isn't a typo. That's adding transparency to the colour hash, can you reinstate please?

**Comment by greenc05** [comment]
This will need checking with all our supported screen readers before live please

File: packages/components/psammead-podcast-promo/src/components/card-image-wrapper.jsx [hunk 2]
```diff
@@ -7,18 +7,13 @@ import {
 } from '@bbc/gel-foundations/breakpoints';
 
 const CardImageWrapper = styled.div`
-  /* 88px */
```
Comment (RichardPK) [inline packages/components/psammead-podcast-promo/src/components/card-image-wrapper.jsx:10]: _"A code comment is a lie waiting to be told"_, @jroebu14 2021 (I know you didn't come up with it but hey it's 2021 - proper attribution is a myth).

Comment (jroebu14) [reply packages/components/psammead-podcast-promo/src/components/card-image-wrapper.jsx:10]: haha I found the proper attribution which I seemed to have paraphrased

> a comment is a lie waiting to happen
Josh Susser

here's another
> A comment is the code’s way of asking to be more clear
Kent Beck

another good one
> Clear code with no comments is preferable to messy code with clear comments.

The above example is definitely a lie waiting to happen 😆 

Comments are an interesting debate though. Personally I would rarely write comments. I'd think about how the code can be clearer or how a unit test could explain something better since it's harder to lie with unit tests!

File: packages/components/psammead-podcast-promo/src/components/card.jsx [hunk 3]
```diff
@@ -1,11 +1,12 @@
 import styled from '@emotion/styled';
-import { C_GHOST } from '@bbc/psammead-styles/colours';
+import { C_GHOST, C_EBON } from '@bbc/psammead-styles/colours';
 import { GEL_GROUP_4_SCREEN_WIDTH_MIN } from '@bbc/gel-foundations/breakpoints';
 
 const Card = styled.div`
   position: relative;
   background-color: ${C_GHOST};
   display: flex;
+  box-shadow: 0 0 0.3125rem 0.3125rem ${C_EBON}08;
```
Comment (jroebu14) [inline packages/components/psammead-podcast-promo/src/components/card.jsx:9]: is the `08` at the end supposed to be there?

**Review by jroebu14 — APPROVED** [review]
Looks good

File: packages/components/psammead-podcast-promo/src/components/card.jsx (hunk 3 above)
Comment (RichardPK) [reply packages/components/psammead-podcast-promo/src/components/card.jsx:9]: Haha. I defer to https://github.com/bbc/psammead/pull/4214#discussion_r555677574

It's adding a 0.03 transparency to the `${C_EBON}` hash value

File: packages/components/psammead-podcast-promo/src/components/card.jsx (hunk 1 above)
Comment (jroebu14) [reply packages/components/psammead-podcast-promo/src/components/card.jsx]: ooh I didn't that was a thing. Thought you'd have to rgba-ify the hex value

Comment (RichardPK) [reply packages/components/psammead-podcast-promo/src/components/card.jsx]: It's disgustingly unintuitive - flipping between letters & numbers  https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4

Comment (RichardPK) [reply packages/components/psammead-podcast-promo/src/components/card.jsx]: If 22% opacity is `38` then what's 23%?
That's right kids!
It's `3B `
OK, now what's 24%?
Yep you guessed it!
`3D`!

Comment (RichardPK) [reply packages/components/psammead-podcast-promo/src/components/card.jsx]: Oh and uh - because that article just freaked me out over where the AA value goes,

> On web, the alpha hex comes after the 6-char hex.
> On iOS and Android, the alpha hex comes before the 6-char hex.
