### PR TITLE
Change default lang prop in bulletin

### LINKED ISSUE #3428: Radio bulletin - Incorrect lang attribute on visually hidden text on arabic
**Describe the bug**
The radio bulletin on https://www.bbc.com/arabic has some visually hidden text with a lang attribute stating english as the language of this content, this attribute should not be there as the content is not in english.

**Expected behaviour**
The lang attribute should not be there as the content is not in english.

**Screenshots**
Screen Shot 2020-04-27 at 14 45 56

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

### PR DESCRIPTION
**Pull request by EinsteinNjoroge**
Partially resolves #3428 

**Overall change:** _Change default `lang` prop to `null` in psammead-bulletin and apply `lang` attribute to the hidden text if `lang` is defined_

**Code changes:**

- _Change default `lang` prop to null_
- _Apply `lang` attribute if it's defined._
- _Add test for `Arabic` service and update snapshots._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

File: packages/components/psammead-bulletin/src/index.jsx [hunk 1]
```diff
@@ -258,15 +259,13 @@ Bulletin.propTypes = {
...
   offScreenText: string.isRequired,
-  lang: string,
 };
 
 Bulletin.defaultProps = {
   dir: 'ltr',
   image: null,
   isLive: false,
   liveText: 'LIVE',
-  lang: 'en-GB',
```
Comment (DenisHdz) [inline packages/components/psammead-bulletin/src/index.jsx:269]: I think we can leave this prop but set it as `null` by default.

File: packages/components/psammead-bulletin/src/index.jsx [hunk 2]
```diff
@@ -180,11 +180,12 @@ const Bulletin = ({
   isLive,
   liveText,
   offScreenText,
-  lang,
 }) => {
   const isAudio = mediaType === 'audio';
   const bulletinType = isAudio ? 'radio' : 'tv';
   const BulletinWrapper = isAudio ? RadioBulletinWrapper : TVBulletinWrapper;
+  const ctaTextIsEnglish = ctaText === 'Watch' || ctaText === 'Listen';
```
Comment (DenisHdz) [inline packages/components/psammead-bulletin/src/index.jsx]: Looks good, but I was thinking to do this in Simorgh instead, as we do in the `StoryPromo` container with the Live label https://github.com/bbc/simorgh/blob/latest/src/app/containers/StoryPromo/index.jsx#L101. Happy to hear other people thoughts

Comment (EinsteinNjoroge) [reply packages/components/psammead-bulletin/src/index.jsx]: Good idea.
I think that we'll be a better approach to separate the psammead components from our simorgh implementation.

File: packages/components/psammead-bulletin/src/index.test.jsx [hunk 3]
```diff
@@ -1,11 +1,19 @@
...
 /* eslint-disable react/prop-types */
-const BulletinComponent = ({ script, service, isLive, mediaType, ctaText }) => {
+const BulletinComponent = ({
+  script,
+  service,
+  isLive,
+  mediaType,
+  ctaText,
+  dir = 'ltr',
+  lang = null,
```
Comment (DenisHdz) [inline packages/components/psammead-bulletin/src/index.test.jsx:15]: We can remove this now
```suggestion

```

File: packages/components/psammead-bulletin/src/index.test.jsx [hunk 4]
```diff
@@ -31,6 +39,8 @@ const BulletinComponent = ({ script, service, isLive, mediaType, ctaText }) => {
       ctaText={playCtaText}
       isLive={isLive}
       offScreenText={offScreenText}
+      dir={dir}
+      lang={lang}
```
Comment (DenisHdz) [inline packages/components/psammead-bulletin/src/index.test.jsx:43]:
```suggestion

```

File: packages/components/psammead-bulletin/src/index.jsx [hunk 5]
```diff
@@ -185,6 +185,7 @@ const Bulletin = ({
   const isAudio = mediaType === 'audio';
   const bulletinType = isAudio ? 'radio' : 'tv';
   const BulletinWrapper = isAudio ? RadioBulletinWrapper : TVBulletinWrapper;
+  const hiddenTextProps = lang ? { lang } : {};
```
Comment (DenisHdz) [inline packages/components/psammead-bulletin/src/index.jsx:188]: I think this will just add the `lang` prop as a boolean and we want `lang={lang}`.

File: packages/components/psammead-bulletin/src/index.jsx [hunk 6]
```diff
@@ -213,7 +214,7 @@ const Bulletin = ({
               // eslint-disable-next-line jsx-a11y/aria-role
               <span role="text">
                 {offScreenText && (
-                  <VisuallyHiddenText lang={lang}>
```
Comment (DenisHdz) [inline packages/components/psammead-bulletin/src/index.jsx]: We can keep this as it was, because if the language is not passed it will be `lang=null` which is the same that `const hiddenTextProps = lang ? { lang } : {};` will return.

File: packages/components/psammead-bulletin/src/index.test.jsx (hunk 4 above)
Comment (EinsteinNjoroge) [reply packages/components/psammead-bulletin/src/index.test.jsx:43]: @DenisHdz The intention here is to test for the right output when the `lang` prop is passed in.

File: packages/components/psammead-bulletin/src/index.test.jsx (hunk 3 above)
Comment (EinsteinNjoroge) [reply packages/components/psammead-bulletin/src/index.test.jsx:15]: https://github.com/bbc/psammead/pull/3430#discussion_r416735056

File: packages/components/psammead-bulletin/src/index.test.jsx (hunk 4 above)
Comment (DenisHdz) [reply packages/components/psammead-bulletin/src/index.test.jsx:43]: Of course, we need it for the other snapshots https://github.com/bbc/psammead/pull/3430/files#diff-5ae3e98c9edd526e83ba2518475fdcafR67 👍

**Review by DenisHdz — APPROVED** [review]
Thanks for the changes 👍

**Review by OlgaLyubin — APPROVED** [review]
Looks good 👍

**Comment by EinsteinNjoroge** [comment]
This PR doesn't need testing at the component level, it will be tested once it's pulled in to `simorgh`
