### PR TITLE
high contrast media indicator icons

### LINKED ISSUE #786: Media indicator SVG stays dark on high contrast mode
**Describe the bug**
When using the high contrast mode on PC, and with colour preferences changed in Firefox, the media indicator SVG icon stays dark and it's hard to see.

image

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to www.stage.bbc.com/igbo
2. Go to Firefox preferences
3. Look for the Language and Appearance section
image
4. Go to Colours
5. Set override to Always
6. Make sure "Use system colours" is **not** ticked
7. Set colours to a black/dark background and text that can be read (something bright)
image
8. Go back to the Igbo front page - icons are now hard to see
9. Also look at with a custom high contrast mode on PC

**Expected behaviour**
Icon should be visible regardless of what colours you have selected

**Screenshots**
Current:
image

Expected:
image
(although should probably talk to Catharine and UX)

### PR DESCRIPTION
**Pull request by andrew-nowak**
Resolves #786 

**Overall change:** Use `currentColor` for the SVG fill.

**Code changes:** Use `currentColor` for the SVG fill.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

File: packages/components/psammead-media-indicator/src/mediaIcons.jsx [hunk 1]
```diff
@@ -1,12 +1,12 @@
 import React from 'react';
 import styled from 'styled-components';
-import { C_EBON } from '@bbc/psammead-styles/colours';
 import { GEL_SPACING_HLF } from '@bbc/gel-foundations/spacings';
 
+// `currentColor` has been used to address high contrast mode in Firefox.
```
Comment (greenc05) [inline packages/components/psammead-media-indicator/src/mediaIcons.jsx]: Can we please update this comment so it's correct? `currentColor` has been used so that this can be seen when a user changes colour preferences in Firefox.

**Comment by andrew-nowak** [comment]
Checked this also works with windows high contrast mode & customising colour schemes in windows high contrast mode (on ie11)

IMG_0657
IMG_1689

**Review by ghost — APPROVED** [review]

**Review by j-pendlebury — APPROVED** [review]

**Comment by david-boydell** [comment]
All good, ready for merge.
