### PR TITLE
Social embed amp validation fix

### LINKED ISSUE #6367: Social Embed - fix AMP validation error
**Describe the bug**

Fix the AMP validation error - see screenshot below.

**To Reproduce**

Run https://www.test.bbc.com/kyrgyz/23292889.amp through AMP Validator.

**To Fix**

Move `providerStyles` https://github.com/bbc/simorgh/blob/latest/src/app/containers/SocialEmbed/index.jsx#L22-L35 into the CanonicalSocialEmbed component within Psammead. This will separate them from the AMP stylesheet.

**Expected behaviour**

No validation error.

**Screenshots**

image

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by oluoluoxenfree**
Resolves bbc/simorgh#6367

**Overall change:** _A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

File: packages/components/psammead-social-embed/src/Canonical/index.jsx [hunk 1]
```diff
@@ -21,12 +21,25 @@ const OEmbed = styled.div`
...
     script: 'https://platform.twitter.com/widgets.js',
+    styles: `
+      .twitter-tweet {
+        margin-top: 0 !important;
+        margin-bottom: 0 !important;
+      }
+    `,
   },
   youtube: {
-    styles: css`
```
Comment (simonsinclair) [inline packages/components/psammead-social-embed/src/Canonical/index.jsx:29]: 👍

File: packages/components/psammead-social-embed/package.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "@bbc/psammead-social-embed",
-  "version": "1.0.2",
+  "version": "1.0.3",
```
Comment (simonsinclair) [inline packages/components/psammead-social-embed/package.json]: - As these styles didn't exist in `1.0.2`, we should probably mark this as a `minor` update rather than a `patch`. Please can we amend this to `1.1.0`?
- This version should be updated in `package-lock.json` too.

File: packages/components/psammead-social-embed/CHANGELOG.md [hunk 3]
```diff
@@ -1,11 +1,12 @@
...
-| 1.0.2 | [PR#3397](https://github.com/bbc/psammead/pull/3397) Talos - Bump Dependencies - @bbc/psammead-styles |
-| 1.0.1 | [PR#3388](https://github.com/bbc/psammead/pull/3388) Update react-helmet to 6.0.0 |
-| 1.0.0 | [PR#3349](https://github.com/bbc/psammead/pull/3349) Resolve a11y issues and release version one. |
-| 0.1.0-alpha.4 | [PR#3319](https://github.com/bbc/psammead/pull/3319) Remove dependency on @bbc/psammead-oembed.   |
-| 0.1.0-alpha.3 | [PR#3311](https://github.com/bbc/psammead/pull/3311) Transpile with @loadable/babel-plugin.       |
-| 0.1.0-alpha.2 | [PR#3298](https://github.com/bbc/psammead/pull/3298) Add webpackChunkName to dynamic import.      |
-| 0.1.0-alpha.1 | [PR#3217](https://github.com/bbc/psammead/pull/3217) Initial creation of package.                 |
+| Version       | Description                                                                                           |
+| ------------- | ----------------------------------------------------------------------------------------------------- |
+| 1.0.3         | [PR?]() Add CSS styles for AMP                                                                        |
```
Comment (simonsinclair) [inline packages/components/psammead-social-embed/CHANGELOG.md]: - Oops, we're missing the PR information here.
- Also the description should probably say something like: `Update Canonical provider styles`

**Review by simonsinclair — COMMENTED** [review]
Thanks for picking this up, Olu! I've left a few comments below.

File: packages/components/psammead-social-embed/CHANGELOG.md [hunk 4]
```diff
@@ -1,11 +1,12 @@
...
-| 1.0.2 | [PR#3397](https://github.com/bbc/psammead/pull/3397) Talos - Bump Dependencies - @bbc/psammead-styles |
-| 1.0.1 | [PR#3388](https://github.com/bbc/psammead/pull/3388) Update react-helmet to 6.0.0 |
-| 1.0.0 | [PR#3349](https://github.com/bbc/psammead/pull/3349) Resolve a11y issues and release version one. |
-| 0.1.0-alpha.4 | [PR#3319](https://github.com/bbc/psammead/pull/3319) Remove dependency on @bbc/psammead-oembed.   |
-| 0.1.0-alpha.3 | [PR#3311](https://github.com/bbc/psammead/pull/3311) Transpile with @loadable/babel-plugin.       |
-| 0.1.0-alpha.2 | [PR#3298](https://github.com/bbc/psammead/pull/3298) Add webpackChunkName to dynamic import.      |
-| 0.1.0-alpha.1 | [PR#3217](https://github.com/bbc/psammead/pull/3217) Initial creation of package.                 |
+| Version       | Description                                                                                           |
+| ------------- | ----------------------------------------------------------------------------------------------------- |
+| 1.1.0         | [PR3450](https://github.com/bbc/psammead/pull/3450) Update Canonical provider styles                  |
```
Comment (simonsinclair) [inline packages/components/psammead-social-embed/CHANGELOG.md]:
```suggestion
| 1.1.0         | [PR#3450](https://github.com/bbc/psammead/pull/3450) Update Canonical provider styles                 |
```

**Review by simonsinclair — APPROVED** [review]
Nice work, Olu. 👍

**Review by ghost — APPROVED** [review]
👍
