### PR TITLE
Media Player - Limit Unnecessary re-renders

### LINKED ISSUE #5528: Media Player reloads when using skip to content
**Describe the bug**
The Media Player will reload when clicking skip to content. This is most noticeable when you are in the middle of playing media because the media will go back to the beginning after clicking skip to content. This is a problem for any page type that uses the Media Player e.g. MAP, article pages, live radio pages.

**To Reproduce**

1. Go to https://www.stage.bbc.com/pidgin/23248703
2. Click on the video to play the content
3. Tab to the skip to content link
4. Observe the video reloads and shows the video placeholder

**Expected behaviour**
Video should resume playing after skipping to content.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by ryanmccombe**
Resolves https://github.com/bbc/simorgh/issues/5528

**Overall change:**
Limit unnecessary re-rendering of the component, to prevent the iframe from resetting

This was due to upstream components creating new `mediaInfo` objects that contain the same content as the previous object

**Code changes:**

- Memoise the component based on a deep equality check

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Automated jest tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

File: packages/components/psammead-media-player/src/index.jsx [hunk 1]
```diff
@@ -76,6 +77,11 @@ export const CanonicalMediaPlayer = ({
   );
 };
 
+// Component receives a "mediaInfo" object prop - this can cause unnecessary
+// re-renders when the object reference changes, but the content is the same.
+// We only rerender if the prevProps and nextProps fail deep equality check
+export const CanonicalMediaPlayer = memo(CanonicalMediaPlayerComponent, equals);
+
```
Comment (RichardPK) [inline packages/components/psammead-media-player/src/index.jsx:84]: This may be unnecessarily explicit, as I'm describing essentially what ramda equals does implicitly, but, for future readability - I'm not sure it's clear that equals is being passed prevProps and nextProps?

I quite like the model of passing a function `isEqual` as the second argument in the memo and then declaring the function along these lines: (though I realise === may always evaluate to false even if the objects are principally 'the same', so may need rearranging)

```
const isEqual = (prevProps, nextProps) => {
  return prevProps === nextProps
}
```

I think this makes it clearer what's going on and maybe negates the need for adding comments?

Comment (ryanmccombe) [reply packages/components/psammead-media-player/src/index.jsx:84]: cheers 👍 added wrapping function

we still need the deep equality check as `===` just checks if the objects are the same instance, ie, the same place in memory

the bug we're dealing with is parent components creating an entirely new object and passing it down - but that object has all the same values as the previous one

different objects will fail the `===`  check but, if they have the same content, they'll pass the ramda `equals` check

Screen Shot 2020-03-11 at 17 49 21

Comment (ryanmccombe) [reply packages/components/psammead-media-player/src/index.jsx:84]: CI is failing because this wrapping function doesn't have test coverage 🤣

Comment (RichardPK) [reply packages/components/psammead-media-player/src/index.jsx:84]: -0.1% you naughty boy.

**Review by RichardPK — APPROVED** [review]
🚢

**Review by karinathomasbbc — APPROVED** [review]
