### PR TITLE
Swaps REITH_SERIF_LIGHT for REITH_SANS_BOLD_ITALIC

### LINKED ISSUE #339: Swap Serif Light for Sans Italic Bold
**Describe the bug**
We have 6 core fonts in news articles, we have 1 of them wrong

https://github.com/bbc/psammead/blob/latest/.storybook/config.js#L45 

**Dev change**
Replace `F_REITH_SERIF_LIGHT` with `F_REITH_SANS_ITALIC_BOLD`

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/psammead/labels/bug)

### PR DESCRIPTION
**Pull request by twinlensreflex**
Resolves #339 

**Overall change:** 

I have swapped `F_REITH_SERIF_LIGHT` for `F_REITH_SANS_BOLD_ITALIC` in https://github.com/bbc/psammead/blob/latest/.storybook/config.js

**Code changes:**

- Config changed to pull in `REITH_SANS_BOLD_ITALIC` and use in GlobalStyling instead of `REITH_SERIF_LIGHT`

---
- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [x] Test engineer approval

### CODE REVIEW

File: .storybook/config.js [hunk 1]
```diff
@@ -13,12 +13,11 @@ import {
   F_REITH_SANS_REGULAR,
   F_REITH_SANS_ITALIC,
   F_REITH_SANS_BOLD,
-  F_REITH_SERIF_LIGHT,
```
Comment (sareh) [inline .storybook/config.js:16]: Could you please increment the top-level version number in `package.json` and `package-lock.json` and update the changelog?

File: packages/components/psammead-image-placeholder/package-lock.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "@bbc/psammead-image-placeholder",
-  "version": "0.1.8",
```
Comment (sareh) [inline packages/components/psammead-image-placeholder/package-lock.json]: You shouldn't need to update this file.

**Review by sareh — CHANGES_REQUESTED** [review]
Looks good - just some package admin needed!

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,7 +1,7 @@
 # Psammead Changelog
 
-| Version | Description |
-|---------|-------------|
-| 1.1.0   | [PR#336](https://github.com/BBC/psammead/pull/336) Add RTL Storybook add-on for testing |
-| 0.1.1   | [PR#354](https://github.com/BBC-News/psammead/pull/354) Update README and add initial changelog. |
-
+| Version | Description                                                                                           |
```
Comment (pjlee11) [inline CHANGELOG.md]:
```suggestion

<!-- prettier-ignore -->
| Version | Description                                                                                           |
```

If you put prettier ignore before `| Version | Description   |` it will stop the auto linting which some in the team complain about

File: CHANGELOG.md [hunk 4]
```diff
@@ -1,7 +1,9 @@
 # Psammead Changelog
 
-| Version | Description |
-|---------|-------------|
-| 1.1.0   | [PR#336](https://github.com/BBC/psammead/pull/336) Add RTL Storybook add-on for testing |
-| 0.1.1   | [PR#354](https://github.com/BBC-News/psammead/pull/354) Update README and add initial changelog. |
 
+<!-- prettier-ignore -->
+| Version | Description                                                                                           |
```
Comment (pjlee11) [inline CHANGELOG.md]:
```suggestion
| Version | Description |
```

File: CHANGELOG.md [hunk 5]
```diff
@@ -1,7 +1,9 @@
...
+| ------- | ----------------------------------------------------------------------------------------------------- |
```
Comment (pjlee11) [inline CHANGELOG.md]:
```suggestion
|---------|-------------|
```

File: CHANGELOG.md [hunk 6]
```diff
@@ -1,7 +1,9 @@
...
+| 1.1.1   | [PR#403](https://github.com/BBC/psammead/pull/402) Update REITH_SERIF_LIGHT to REITH_SANS_BOLD_ITALIC |
+| 1.1.0   | [PR#336](https://github.com/BBC/psammead/pull/336) Add RTL Storybook add-on for testing               |
```
Comment (pjlee11) [inline CHANGELOG.md]:
```suggestion
| 1.1.0   | [PR#336](https://github.com/BBC/psammead/pull/336) Add RTL Storybook add-on for testing |
```

File: CHANGELOG.md [hunk 7]
```diff
@@ -1,7 +1,9 @@
...
+| 0.1.1   | [PR#354](https://github.com/BBC-News/psammead/pull/354) Update README and add initial changelog.      |
```
Comment (pjlee11) [inline CHANGELOG.md]:
```suggestion
| 0.1.1   | [PR#354](https://github.com/BBC-News/psammead/pull/354) Update README and add initial changelog. |
```

**Review by pjlee11 — DISMISSED** [review]
Nice work!

File: CHANGELOG.md [hunk 8]
```diff
@@ -1,7 +1,9 @@
 # Psammead Changelog
 
+
+<!-- prettier-ignore -->
 | Version | Description |
 |---------|-------------|
+| 1.1.1   | [PR#403](https://github.com/BBC/psammead/pull/402) Update REITH_SERIF_LIGHT to REITH_SANS_BOLD_ITALIC |
```
Comment (dr3) [inline CHANGELOG.md]:
```suggestion
| 1.1.1   | [PR#403](https://github.com/BBC/psammead/pull/402) Update to use REITH_SANS_BOLD_ITALIC instead of REITH_SERIF_LIGHT in storybook |
```

**Review by dr3 — CHANGES_REQUESTED** [review]
LGTM, just a small tweak

**Review by dr3 — APPROVED** [review]

**Review by pjlee11 — APPROVED** [review]

**Review by sareh — APPROVED** [review]
