### PR TITLE
Fix StoryPromo font size on IE11

### LINKED ISSUE #1988: IE11 does not support nested media queries
**Describe the bug**
IE11 does not support nested media queries

**To Reproduce**
This was highlighted in #1987 where the previously nested media query font-size and line-height were not being applied to the screen width specified in the nested media query in IE11 but was being applied in Chrome. 

**Expected behaviour**
All styling for the different screen widths should be applied similarly across supported browsers. 

Fixing this might mean refactoring code so that media queries do not need to be nested in the future (this is what was done in #1987 )

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by Bopchy**
Resolves #1988 

**Overall change:** _Fixes StoryPromo font size appearing smaller in IE11._

**Code changes:**

- _Get `font-size` and `line-height` from script._
- _Update snapshots._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

File: packages/components/psammead-story-promo/src/index.jsx [hunk 1]
```diff
@@ -149,7 +148,16 @@ export const Headline = styled.h3`
 
   @media (min-width: ${GEL_GROUP_3_SCREEN_WIDTH_MIN}) {
     ${({ script, topStory }) =>
-      script && (topStory ? getParagon(script) : getGreatPrimer(script))}
+      script &&
+      (topStory
+        ? css`
+            font-size: ${script.paragon.groupD.fontSize / 16}rem;
```
Comment (dr3) [inline packages/components/psammead-story-promo/src/index.jsx]: Howcome this is needed? Do the `getGreatPrimer` and `getParagon` functions not work as expected? Or are we trying to use 1 group over 2 breakpoints?

Comment (Bopchy) [reply packages/components/psammead-story-promo/src/index.jsx]: It's needed for IE11 - because it wasn't picking up on the font-size and line-height specified here https://github.com/bbc/psammead/blob/f45a59d02dcd9f9120da9d9b6101dc7f2cdf37c2/packages/utilities/gel-foundations/src/getTypeSizes.js#L30 since what is returned by either getGreatPrimer() or getParagon() will have a nested media-query, and IE11 doesn't support nested media queries

Comment (dr3) [reply packages/components/psammead-story-promo/src/index.jsx]: Ohhhh hmmm thats annoying of IE :P

Comment (dr3) [reply packages/components/psammead-story-promo/src/index.jsx]: Ohhhh hmmm thats annoying of IE :P Any opinions @sareh @pjlee11 @jblaut? This PR works, but if this is gunna keep coming up, we may need to reevaluate our font size logic

Comment (pjlee11) [reply packages/components/psammead-story-promo/src/index.jsx]: Is it only nested media queries that IE11 doesn't support? I'm interested in how we currently do this on the PAL, maybe we only have a single level of media queries ...

Comment (dr3) [reply packages/components/psammead-story-promo/src/index.jsx]: It feels unique to story promo, where it switches typography at different breakpoints, which is  very uncommon, maybe were ok with it being in this 1 place?

File: packages/components/psammead-story-promo/src/index.jsx [hunk 2]
```diff
@@ -149,7 +148,16 @@ export const Headline = styled.h3`
 
   @media (min-width: ${GEL_GROUP_3_SCREEN_WIDTH_MIN}) {
     ${({ script, topStory }) =>
-      script && (topStory ? getParagon(script) : getGreatPrimer(script))}
+      script &&
+      (topStory
+        ? css`
```
Comment (ghost) [inline packages/components/psammead-story-promo/src/index.jsx]: Could be pull this out to something like 
```js
const getHeadlineFontStyle = (script, topStory) => {
  const type = topStory ? 'paragon' : 'greatPrimer';
  
  const lineHeight = script[type].groupD.fontSize / 16
  const fontSize = script[type].groupD.fontSize / 16

  return css`
  font-size: ${lineHeight}rem;
  line-height: ${fontSize}rem; 
  `
}
```

**Review by ghost — CHANGES_REQUESTED** [review]
Resolve conflicts

File: packages/components/psammead-story-promo/src/index.jsx [hunk 3]
```diff
@@ -139,6 +138,16 @@ const InlineMediaIndicator = styled.div`
       `}
 `;
 
+const getHeadlineFontStyle = (script, type) => {
```
Comment (dr3) [inline packages/components/psammead-story-promo/src/index.jsx]: Above this line, can you write a comment about why this is needed please :)

**Review by dr3 — COMMENTED** [review]
LGTM after the comment, not ideal to have an edge case, but a good solution seeing as this is needed :) nice work :D

File: packages/components/psammead-story-promo/src/index.jsx [hunk 4]
```diff
@@ -149,7 +158,10 @@ export const Headline = styled.h3`
 
   @media (min-width: ${GEL_GROUP_3_SCREEN_WIDTH_MIN}) {
     ${({ script, topStory }) =>
-      script && (topStory ? getParagon(script) : getGreatPrimer(script))}
+      script &&
```
Comment (ghost) [inline packages/components/psammead-story-promo/src/index.jsx]: With this https://github.com/bbc/psammead/pull/1987#discussion_r321116701 suggestion you could simplify this to

```js
${({ script, topStory }) => script && getHeadlineFontStyle(script, topStory)}
```

**Review by ghost — APPROVED** [review]

**Review by dr3 — APPROVED** [review]
